# Generated by Django 4.2.6 on 2023-10-08 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_teacher_alter_subject_name_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="teacher_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.teacher_id",
            ),
            preserve_default=False,
        ),
    ]
